export const PRODUCTS_REQUEST = 'PRODUCTS_REQUIST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';

export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUIST';
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL';
