export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';

export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST';
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL';

export const PRODUCTS_DELETE_REQUEST = 'PRODUCTS_DELETE_REQUEST';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_FAIL = 'PRODUCTS_DELETE_FAIL';

export const PRODUCTS_CREATE_REQUEST = 'PRODUCTS_CREATE_REQUEST';
export const PRODUCTS_CREATE_SUCCESS = 'PRODUCTS_CREATE_SUCCESS';
export const PRODUCTS_CREATE_FAIL = 'PRODUCTS_CREATE_FAIL';
export const PRODUCTS_CREATE_RESET = 'PRODUCTS_CREATE_RESET';

export const PRODUCTS_UPDATE_REQUEST = 'PRODUCTS_UPDATE_REQUEST';
export const PRODUCTS_UPDATE_SUCCESS = 'PRODUCTS_UPDATE_SUCCESS';
export const PRODUCTS_UPDATE_FAIL = 'PRODUCTS_UPDATE_FAIL';
export const PRODUCTS_UPDATE_RESET = 'PRODUCTS_UPDATE_RESET';
